openapi: 3.0.3
info:
  title: Fruits Ecommerce
  version: 1.0.11

tags:
  - name: user
    description: Operations about user
  - name: product
    description: Operations about product
  - name: cart
    description: Operations about card


paths:
  /register:
    post:
      tags:
        - user
      summary: register user
      description: This can only be done by the logged in user.
      operationId: registerUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
            examples:
              default:
                value:
                  name: "defaultUser"
                  email: "defaultuser@example.com"
                  password: "Default"
      responses:
        '200':
          description: RegisterResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              examples:
                default:
                  value:
                    message: "defaultUser"
                    email: "defaultuser@example.com"
        '403':
          description: User error
          content:
            application/json:
              examples:
                default:
                  value:
                    error: "User error"
  /registerClient:
    post:
      tags:
        - user
      summary: register user as a customer
      description: This can only be done by the logged in user.
      operationId: registerClient
      requestBody:
        description: Created client object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
            examples:
              default:
                value:
                  name: "defaultUser"
                  email: "defaultuser@example.com"
                  password: "Default"
                  shippingAddress:
                    content:
                      application/json:
                        schema:
                          $ref: '#/components/schemas/ShipAddDTO'
                  billingAddress:
                    content:
                      application/json:
                        schema:
                          $ref: '#/components/schemas/BillAddDTO'
                  creditInfo:
                    content:
                      application/json:
                        schema:
                          $ref: '#/components/schemas/CreditDTO'
      responses:
        '200':
          description: RegisterResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              examples:
                default:
                  value:
                    message: "defaultUser"
                    email: "defaultuser@example.com"
        '403':
          description: User error
          content:
            application/json:
              examples:
                default:
                  value:
                    error: "User error"
  /login:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      requestBody:
        description: login user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
            examples:
              default:
                value:
                  email: "defaultuser@example.com"
                  password: "Default"
      responses:
        '200':
          description: AuthenticationResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
                examples:
                  default:
                     value:
                      message: "defaultUser"
                      email: "defaultuser@example.com"
        '403':
          description: Invalid username/password supplied
  /products:
    post:
      tags:
        - product
      summary: create product
      description: This operation to add a new product .
      operationId: addProduct
      requestBody:
        description: Created product object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
            examples:
              default:
                value:
                  image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                  name: "apple"
                  unit: "per kg"
                  price: 50
                  description: "The Fresh and Natural offers you a complete range of all types of local and imported fresh and quality vegetables and fruit all over the Kingdom"
      responses:
        '200':
          description: addProductResponse
          content:
            text/plain:
              schema:
                type: string
                example: "Product created successfully"
        '403':
          description: User error
          content:
            application/json:
              examples:
                default:
                  value:
                    error: "product error"
    get:
      tags:
        - product
      summary: Get some products
      description: Retrieve a list of some products and return them
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: int
            minimum: 0
          description: Minimum range of the product
        - name: size
          in: query
          required: true
          schema:
            type: int
            minimum: 0
          description: Maximum range of the product
      responses:
        '200':
          description: A list of products within the specified range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
              examples:
                example-1:
                  summary: Example product response
                  value:
                    - id: "2"
                      image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                      name: "example1"
                      unit: "per kg"
                      price: 50
                      description: "example 1 description"
                    - id: "3"
                      image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                      name: "example2"
                      unit: "per kg"
                      price: 50
                      description: "example 2 description"
                    - id: "3"
                      image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                      name: "example3"
                      unit: "per kg"
                      price: 50
                      description: "example 3 description"
        '404':
          description: No products found
          content:
            text/plain:
              schema:
                type: string
                example: "No products found"
  /carts:
    post:
      tags:
        - cart
      summary: add product to card
      description: customer can add product to his card.
      operationId: addToCard
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: long
            minimum: 0
          description: id of user
        - name: productId
          in: query
          required: true
          schema:
            type: long
            minimum: 0
          description: id of product
      responses:
        '200':
          description: addProductResponse
          content:
            text/plain:
              schema:
                type: string
                example: "Product added successfully"
        '403':
          description: User error
          content:
            application/json:
              examples:
                default:
                  value:
                    error: "error"
    get:
      tags:
        - card
      summary: Get cart
      description: Retrieve the cart of customer
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: long
            minimum: 0
          description: id of user
      responses:
        '200':
          description: the cart of customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDisplayResponse'
        '404':
          description: No cart found
          content:
            text/plain:
              schema:
                type: string
                example: "No cart found"


components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
    UserDTO:
      type: object
      properties:
        id:
          type: long
          example: 10
        username:
          type: string
          example: theUser
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
      xml:
        name: user
    AuthenticationResponse:
      type: object
      properties:
        message:
          type: string
          example: response
        email:
          type: string
          example: theUser@gmail.com
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: response
        email:
          type: string
          example: theUser@gmail.com
    ProductDTO:
      type: object
      properties:
        id:
          type: long
          example: 2
        image:
          type: string
          example: https://images.app.goo.gl/1ovQuh4HqqdQAr949
        name:
          type: string
          example: apple
        unit:
          type: string
          example: per kg
        price:
          type: double
          example: 50.00
        description:
          type: string
          example: description for product apple
    ShipAddDTO:
      type: object
      properties:
        id:
          type: long
          example: 2
        addressL1:
          type: string
          example: hella
        addressL2:
          type: string
          example: bella
        postal_code:
          type: string
          example: 12547
    BillAddDTO:
      type: object
      properties:
        id:
          type: long
          example: 2
        addressL1:
          type: string
          example: hella
        addressL2:
          type: string
          example: bella
        postal_code:
          type: string
          example: 12547
    CreditDTO:
      type: object
      properties:
        id:
          type: long
          example: 2
        card_number:
          type: string
          example: "1234-5678-9101-1121"
        expiry_date:
          type: string
          format: "MM/YYYY"
          example: "12/2025"
        cvv:
          type: integer
          example: 123
    CustomerDTO:
      type: object
      properties:
        id:
          type: long
          example: 10
        username:
          type: string
          example: theUser
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        ShipAddDTO:
          type: object
          properties:
            id:
              type: long
              example: 2
            addressL1:
              type: string
              example: hella
            addressL2:
              type: string
              example: bella
            postal_code:
              type: string
              example: 12547
        BillAddDTO:
          type: object
          properties:
            id:
              type: long
              example: 2
            addressL1:
              type: string
              example: hella
            addressL2:
              type: string
              example: bella
            postal_code:
              type: string
              example: 12547
        CreditDTO:
          type: object
          properties:
            id:
              type: long
              example: 2
            card_number:
              type: string
              example: "1234-5678-9101-1121"
            expiry_date:
              type: string
              format: "MM/YYYY"
              example: "12/2025"
            cvv:
              type: integer
              example: 123
    CartDisplayResponse:
      type: object
      properties:
        ProductsDetails:
          type: array
          items:
            properties:
              id:
                type: long
                example: 2
              image:
                type: string
                example: https://images.app.goo.gl/1ovQuh4HqqdQAr949
              name:
                type: string
                example: apple
              price:
                type: double
                example: 50.00
              quantity:
                type: integer
                example: 5
              total:
                type: long
                example: 5
        CartTotal:
          type: object
          properties:
            subTotal:
              type: long
              example: 125
            shipCost:
              type: long
              example: 45
            total:
              type: long
              example: 170
