openapi: 3.0.3
info:
  title: Fruits Ecommerce
  version: 1.0.11

tags:
  - name: user
    description: Operations about user
  - name: product
    description: Operations about product
paths:
  /register:
    post:
      tags:
        - user
      summary: register user
      description: This can only be done by the logged in user.
      operationId: registerUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
            examples:
              default:
                value:
                  name: "defaultUser"
                  email: "defaultuser@example.com"
                  password: "Default"
      responses:
        '200':
          description: RegisterResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              examples:
                default:
                  value:
                    message: "defaultUser"
                    email: "defaultuser@example.com"
        '403':
          description: User error
          content:
            application/json:
              examples:
                default:
                  value:
                    error: "User error"
  /login:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      requestBody:
        description: login user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
            examples:
              default:
                value:
                  email: "defaultuser@example.com"
                  password: "Default"
      responses:
        '200':
          description: AuthenticationResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
                examples:
                  default:
                     value:
                      message: "defaultUser"
                      email: "defaultuser@example.com"
                      accessToken: "fxsaasgfdnhcnmccggmcgg"
        '403':
          description: Invalid username/password supplied
  /products:
    post:
      tags:
        - product
      summary: create product
      description: This operation to add a new product .
      operationId: addProduct
      requestBody:
        description: Created product object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
            examples:
              default:
                value:
                  image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                  name: "apple"
                  unit: "per kg"
                  price: 50
                  description: "The Fresh and Natural offers you a complete range of all types of local and imported fresh and quality vegetables and fruit all over the Kingdom"
      responses:
        '200':
          description: addProductResponse
          content:
            text/plain:
              schema:
                type: string
                example: "Product created successfully"
        '403':
          description: User error
          content:
            application/json:
              examples:
                default:
                  value:
                    error: "product error"
    get:
      tags:
        - product
      summary: Get some products
      description: Retrieve a list of some products and return them
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: int
            minimum: 0
          description: Minimum range of the product
        - name: size
          in: query
          required: true
          schema:
            type: int
            minimum: 0
          description: Maximum range of the product
      responses:
        '200':
          description: A list of products within the specified range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
              examples:
                example-1:
                  summary: Example product response
                  value:
                    - id: "2"
                      image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                      name: "example1"
                      unit: "per kg"
                      price: 50
                      description: "example 1 description"
                    - id: "3"
                      image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                      name: "example2"
                      unit: "per kg"
                      price: 50
                      description: "example 2 description"
                    - id: "3"
                      image: "https://images.app.goo.gl/1ovQuh4HqqdQAr949"
                      name: "example3"
                      unit: "per kg"
                      price: 50
                      description: "example 3 description"
        '404':
          description: No products found
          content:
            text/plain:
              schema:
                type: string
                example: "No products found"


components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
    UserDTO:
      type: object
      properties:
        id:
          type: long
          example: 10
        username:
          type: string
          example: theUser
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
      xml:
        name: user
    AuthenticationResponse:
      type: object
      properties:
        message:
          type: string
          example: response
        email:
          type: string
          example: theUser@gmail.com
        accessToken:
          type: string
          example: fxsaasgfdnhcnmccggmcgg
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          example: response
        email:
          type: string
          example: theUser@gmail.com
    ProductDTO:
      type: object
      properties:
        id:
          type: long
          example: 2
        image:
          type: string
          example: https://images.app.goo.gl/1ovQuh4HqqdQAr949
        name:
          type: string
          example: apple
        unit:
          type: string
          example: per kg
        price:
          type: double
          example: 50.00
        description:
          type: string
          example: description for product apple

